#ifndef LEXEMES.H  
#define    MOD_TOK '%'
#define    ADD_TOK '+'
#define    SUB_TOK '-'
#define    MUL_TOK '*'
#define    DIV_TOK '/'
#define  MOD_EQUAL_TOK 384
#define  PLUS_EQUAL_TOK  385                
#define  MINUS_EQUAL_TOK   386  
#define  MUL_EQUAL_TOK       387
#define  DIV_EQUAL_TOK       388
#define    EQUAL_TOK     '='
#define    BITWISE_AND_TOK '&'      
#define    BITWISE_OR_TOK    '|'    
#define    BITWISE_XOR_TOK     '^'  
#define  COMPOUND_BITWISE_AND    389   
#define  COMPOUND_BITWISE_OR     390
#define  COMPOUND_BITWISE_XOR      391  
#define    BITWISE_COMPLEMENT        '~'
#define  SHIFT_LEFT      392
#define  SHIFT_RIGHT      393
#define  INC_TOK     394
#define  DEC_TOK     395
#define  AND_TOK     396
#define  OR_TOK      397
#define    NOT       '!'
#define  EQUAL_EQUAL_TOK 398    
#define    GT_TOK        '>'
#define    LT_TOK        '<'
#define  NOT_EQUAL_TOK     399  
#define  GT_EQUAL_TOK        400
#define  LT_EQUAL_TOK        401
#define    LPAREN_TOK        '('
#define    RPAREN_TOK        ')'
#define    LBRACES_TOK       '['
#define    RBRACES_TOK       ']'
#define    LCROCHETS_TOK     '{'
#define    RCROCHETS_TOK     '}'
#define      COMMA_TOK       ','
#define      SEMICOLON_TOK     ';'  
#define    TERNARY_OP_QUESTION   '?'    
#define    TERNARY_OP_COLON      ':'
#define     ARROW 402     
#define AUTO_TOK        500
#define BREAK_TOK       501
#define CASE_TOK        502
#define CHAR_TOK        503
#define CONST_TOK       504
#define CONTINUE_TOK    505
#define DEFAULT_TOK     506
#define DO_TOK          507
#define DOUBLE_TOK      508
#define ELSE_TOK        509
#define ENUM_TOK        510
#define EXTERN_TOK      511
#define FLOAT_TOK       512
#define FOR_TOK         513
#define GOTO_TOK        514
#define IF_TOK          515
#define INT_TOK         516
#define LONG_TOK        517
#define REGISTER_TOK    518
#define RETURN_TOK      519
#define SHORT_TOK       520
#define SIGNED_TOK      521
#define SIZEOF_TOK      522
#define STATIC_TOK      523
#define STRUCT_TOK      524
#define SWITCH_TOK      525
#define TYPEDEF_TOK     526
#define UNION_TOK       527
#define UNSIGNED_TOK    528
#define VOID_TOK        529
#define VOLATILE_TOK    530
#define WHILE_TOK       531
#define ID_TOK          532
#define INTCONST        533
#define FLOATING_POINT_CONST    534
#define EXPONENTIAL_CONST   535
#define CHARACTER   536
#define STRING  537
#define REFERENCE 538
#define DEREFERENCE 539
#endif